### ISSUE TITLE
Client ID is broken

### ISSUE THREAD

**Issue by ScottG489** [lukapusic/soundcloud-dl#120]
Looks like the client ID you install with in the .scdl.cfg file is broken. I just registered by own client ID with soundcloud and now everything works.

**Comment by flyingrub** [comment]
it's because this project is deprecated as the readme say :)
use https://github.com/flyingrub/scdl.

**Comment by ScottG489** [comment]
Alright thanks, my fault. I think I saw that originally but had issues getting it running. I'll give it a shot again...
